project/location/urls.py
from django.urls import path

from location import views

app_name = 'location'

urlpatterns = [
    path('', views.LocationView.as_view(), name='location_list'),
    path('add/', views.CreateLocationView.as_view(), name='add'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.delete_location, name='delete'),
    path('<int:pk>/activate/', views.activate_location, name='activate'),
]

project/project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('location.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('profile/', include('timesheet.urls')),
]

project/timesheet/urls.py
from django.urls import path

from timesheet import views

app_name = 'timesheet'

urlpatterns = [
    path('start_timesheet/', views.new_timesheet, name='start_timesheet'),
    path('stop_timesheet/', views.stop_timesheet, name='stop_timesheet'),
]

project/location/models.py
from django.db import models


# Create your models here.
class Location(models.Model):
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.city} -> {self.country}"


class Log(models.Model):
    action_choices = (('created', 'created'),
                      ('updated', 'updated'),
                      ('refresh', 'refresh'))
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    action = models.CharField(max_length=10, choices=action_choices)
    url = models.CharField(max_length=100)

project/timesheet/models.py
from django.db import models

# Create your models here.
class Timesheet(models.Model):

    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null=True)

project/userprofile/models.py
from django.db import models


# Create your models here.

project/location/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from location.models import Location


# Create your views here.
class LocationView(LoginRequiredMixin, ListView):
    model = Location
    template_name = 'location/location_index.html'


class CreateLocationView(LoginRequiredMixin, CreateView):
    model = Location
    fields = ['city', 'country']
    template_name = 'location/location_form.html'

    def get_success_url(self):
        return reverse('location:location_list')


class UpdateLocationView(LoginRequiredMixin, UpdateView):
    model = Location
    fields = ['city', 'country']
    template_name = 'location/location_form.html'

    def get_success_url(self):
        return reverse('location:location_list')


@login_required
def delete_location(request, pk):
    Location.objects.filter(id=pk).update(active=0)
    return redirect('location:location_list')


@login_required
def activate_location(request, pk):
    Location.objects.filter(id=pk).update(active=1)
    return redirect('location:location_list')

project/timesheet/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

from timesheet.models import Timesheet


# Create your views here.


@login_required
def new_timesheet(request):
    Timesheet.objects.create(user_id=request.user.id,
                             start_date=datetime.datetime.now())
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def stop_timesheet(request):
    Timesheet.objects.filter(user_id=request.user.id,
                             end_date=None).update(end_date=datetime.datetime.now())
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

project/userprofile/views.py
from django.shortcuts import render

# Create your views here.

project/templates/base.html
<html>
<head>
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>

<body>
<div class="container">
    <div clas="=row">
        <div clas="column">
            <nav>
                <a class="btn" href="/admin">Admin</a>
                {% if request.user.is_authenticated %}
                    {% if ready_to_work is False %}
                        <a href="{% url 'timesheet:stop_timesheet' %}" class="btn btn-danger">Stop Timekeeping</a>
                    {% else %}
                        <a href="{% url 'timesheet:start_timesheet' %}" class="btn btn-success">Start Timekeeping</a>
                    {% endif %}
                    <a class="btn btn-info" href="{% url 'location:location_list' %}">Locations</a>
                    <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
                {% endif %}
            </nav>
        </div>
    </div>
</div>
{% block content %}
{% endblock %}
</body>
</html>

project/templates/location/location_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
    {%  csrf_token %}
    {% for field in form %}
        {{ field.label }} {{ field }} {{ field.error }} <br/>
    {%  endfor %}
    <button type="submit" class="btn btn-danger">Save</button>
    </form>
{% endblock %}

project/templates/location/location_index.html
{% extends 'base.html' %}
{% block content %}

    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>City</th>
            <th>Country</th>
            <th>Active</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in location_list %}
            <tr>
                <td> {{ forloop.counter }}</td>
                <td> {{ item.city }}</td>
                <td> {{ item.country }}</td>
                <td> {% if item.active %}
                    Active
                {% else %}
                    Inactive
                {% endif %}</td>

                <td>
                    <a class="btn btn-success" href="{% url 'location:edit' item.id %}">Edit</a>
                    {% if item.active %}
                        <a class="btn btn-danger" href="{% url 'location:delete' item.id %}">Delete</a>
                    {% else %}
                        <a class="btn btn-warning" href="{% url 'location:activate' item.id %}">Activate</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

     <a class="btn btn-primary" href="{% url 'location:add' %}">Add locations</a>
{% endblock %}